Improve debian packaging (thanks to chugajstyr)

diff --git a/debian/sams2-web.postinst b/debian/sams2-web.postinst
--- a/debian/sams2-web.postinst
+++ b/debian/sams2-web.postinst
@@ -1,2 +1,44 @@
-ln -s /etc/apache2/conf.d/sams2.conf /etc/apache2/sites-enabled/sams2.conf
-chmod 777 /usr/share/sams2/data
+#!/bin/sh
+# postinst script for sams2-web
+#
+# see: dh_installdeb(1)
+
+set -e
+
+# summary of how this script can be called:
+#        * <postinst> `configure' <most-recently-configured-version>
+#        * <old-postinst> `abort-upgrade' <new version>
+#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
+#          <new-version>
+#        * <postinst> `abort-remove'
+#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
+#          <failed-install-package> <version> `removing'
+#          <conflicting-package> <version>
+# for details, see http://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
+
+
+case "$1" in
+    configure)
+	chmod 777 /usr/share/sams2/data
+	if which a2ensite >dev/null 2>&1 ; then
+	    a2ensite -q sams2-web
+	    service apache2 reload
+	fi
+    ;;
+
+    abort-upgrade|abort-remove|abort-deconfigure)
+    ;;
+
+    *)
+        echo "postinst called with unknown argument \`$1'" >&2
+        exit 1
+    ;;
+esac
+
+# dh_installdeb will replace this with shell code automatically
+# generated by other debhelper scripts.
+
+#DEBHELPER#
+
+exit 0
